AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HyperGrowthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: framework/example_lambda
      Handler: entry.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref HyperGrowthLayer
      Events:
        HyperGrowth:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: makefile

  HyperGrowthLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: hypergrowth-layer
      Description: hypergrowth dependencies
      ContentUri: framework/
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HyperGrowthAPI:
    Description: "API Gateway endpoint URL for Prod stage for HyperGrowth function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/example/"
  HyperGrowthFunction:
    Description: "HyperGrowth Lambda Function ARN"
    Value: !GetAtt HyperGrowthFunction.Arn
  HyperGrowthFunctionIamRole:
    Description: "Implicit IAM Role created for HyperGrowth function"
    Value: !GetAtt HyperGrowthFunctionRole.Arn
